# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: Xcode@5
  inputs:
    actions: 'build-for-testing'
    scheme: 'Circlone'
    sdk: 'iphonesimulator'
    configuration: 'Release'
    xcodeVersion: 'default'
- task: Xcode@5
  inputs:
    actions: 'test-without-building'
    scheme: 'Circlone'
    sdk: 'iphonesimulator'
    configuration: 'Release'
    xcodeVersion: 'default'
